config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "tops#index"

  resources :ports do
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  resources :works do
  end

  resources :top do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :work
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  validates :title, presence: {message: "タイトルを入力してください"}
  validates :rate, presence: {message: "選択してください"}
  validates :content, presence: {message: "レビュー内容を記入してください"}


  class << self #average_rateをクラスメソッドにするため、「class << self 〜 end」で囲む
    def average_rate(posts)
      sum_of_rate = 0
      posts.each do |post|
        sum_of_rate = sum_of_rate + post.rate
      end
      sum_of_rate / posts.length
    end
  end

end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/models/work.rb
class Work < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_locale
    layout :layout_by_resource

    protected

    def set_locale
      I18n.locale = locale
    end
  
    def locale
      # ここで言語の切り替えを行う
      @locale ||= params[:locale] || I18n.default_locale
    end

    def layout_by_resource
      if devise_controller?
        "devise"
      else
        "application"
      end
    end


    def after_sign_in_path_for(resource)
      posts_path # ログイン後に遷移するpathを設定
    end

    def after_sign_out_path_for(resource)
      posts_path # ログアウト後に遷移するpathを設定
    end

  
    def configure_permitted_parameters
      added_attrs = [ :name, :kana, :email, :password, :password_confirmation　]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/ports_controller.rb
class PortsController < ApplicationController

def index
  @messages = Message.new

  render layout: false
end


def create
  @messages = Message.new(message_params)
  if @messages.save
    redirect_to ports_path()
  else
    # saveできなければトップ画面へ
    render ''
  end
end


  private

  def message_params
    params.require(:message).permit(
      :name,
      :email,
      :phone_number,
      :text
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # ログインしていなくても入れるアクション名↓↓
  before_action :authenticate, except: [:index, :show]

  before_action :validates_new, only: :create

  def authenticate
    # ログインしていないとログイン画面に飛ばす記述
    redirect_to new_user_session_path() unless user_signed_in?
  end

  def index
    # 全ての作品情報の取得
    @works = Work.all
  end

  def new
    # どの作品にコメントするか
    @work = Work.find(params[:format])
    # 新しいインスタンスの作成
    @post = Post.new
    # ユーザー登録情報の取得
    @user = current_user
  end
  
  def validates_new
    @work = Work.find(params[:post][:work_id])
    @post = Post.new(
      title: post_params[:title],
      rate: post_params[:rate],
      content: post_params[:content],
      work_id: post_params[:work_id],
      user_id: post_params[:user_id]
    )
    render new_post_path() unless @post.valid?
  end

  def create
    # 入力したparamsをストロングパラメーターに代入し新しいインスタンス内に代入
    @post = Post.new(post_params)
    # ポストがsaveできれば作品show画面へ
    if @post.save
      redirect_to post_path(@post.work_id)
    else
      # saveできなければトップ画面へ
      render ''
    end
  end

  def show
    # トップ画面で選択された作品情報の取得
    @work = Work.find(params[:id])
    # Post内のwork_idが選択されたwork.idと同一のpostを@postsに代入
    @posts = Post.where(work_id: @work.id)
    # 役に立ったボタンが押された時に生成されるようにインスタンス作成
    @like = Like.new
  end

  private


  # セキュリティ上の脆弱性対処のためのストロングパラメーター導入
  def post_params
    params.require(:post).permit(
      :title,
      :rate,
      :content,
      :work_id,
    ).merge(user_id: current_user.id)
  end


end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

  def index
    render layout: false
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  layout  'devise'

  def new
    @works = Work.new
  end

  def create
    if Work.create(work_params)
      redirect_to '/works/new'
    else
      render '/works/new'
    end
  end

  private

  def work_params
    params.require(:work).permit(
      :title,
      :content,
      :release,
      :starring,
      :image
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def i18n_url_for(options)
    if options[:locale] == I18n.default_locale
      options[:locale] = nil
    end
    url_for(options)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/posts/_footer.html.haml
.footer
  .footer-main
    .footer-main-up
      .footer-main-up-first
        %ul.footer-main-up-first__ul
          %li.footer-main-up-first__ul__li#title
            Amazonについて
          %li.footer-main-up-first__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              採用情報
          %li.footer-main-up-first__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonについて
          %li.footer-main-up-first__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              プレスリリース
          %li.footer-main-up-first__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonと地球
          %li.footer-main-up-first__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonのコミュニティ
              %br/
              活動
          %li.footer-main-up-first__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              AmazonGlobal
      .footer-main-up-second
        %ul.footer-main-up-second__ul
          %li.footer-main-up-second__ul__li#title
            Amazonでビジネス
          %li.footer-main-up-second__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonで売る
          %li.footer-main-up-second__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              フルフィルメント by Amazon
          %li.footer-main-up-second__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              マケプレプライム
          %li.footer-main-up-second__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonビジネスで法人販売
          %li.footer-main-up-second__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazon Pay（決済サービス）
          %li.footer-main-up-second__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              アソシエイト（アフィリエイト）
          %li.footer-main-up-second__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonで広告掲載をする
          %li.footer-main-up-second__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonで出版
          %li.footer-main-up-second__ul__li
            %i.fas.fa-chevron-right{style: "color:#DDD"}
              = link_to "", class: "footer-main-up-fors__ul__li-text" do
                すべてのサービスを見る
      .footer-main-up-third
        %ul.footer-main-up-third__ul
          %li.footer-main-up-third__ul__li#title
            Amazonでのお支払い
          %li.footer-main-up-third__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonポイント
          %li.footer-main-up-third__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonギフト券
          %li.footer-main-up-third__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazon Mastercard
          %li.footer-main-up-third__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              クレジットカード＆保険
          %li.footer-main-up-third__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              パートナーポイントプログラム
          %li.footer-main-up-third__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonギフト券チャージタイプ
          %li.footer-main-up-third__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              %i.fas.fa-chevron-right{style: "color:#DDD"}
                すべての支払い方法を見る
      .footer-main-up-fors
        %ul.footer-main-up-fors__ul
          %li.footer-main-up-fors__ul__li#title
            ヘルプ＆ガイド
          %li.footer-main-up-fors__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              配送料と配送情報
          %li.footer-main-up-fors__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazon プライム
          %li.footer-main-up-fors__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              商品の返品・交換
          %li.footer-main-up-fors__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text", class: "footer-main-up-fors__ul__li-text" do
              コンテンツと端末の管理
          %li.footer-main-up-fors__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              Amazonアシスタント
          %li.footer-main-up-fors__ul__li
            = link_to "", class: "footer-main-up-fors__ul__li-text" do
              ヘルプ
  .footer-down
    .footer-down-main
      .footer-down-main-box
        .footer-down-main-box-amazon
          amazon
        .footer-down-main-box-language
          %select.footer-down-main-box-language-choice(name="posts")
            %option(value="JP")日本語
            %option(value="EN")英語
            %option(value="ZH")中国語
          .footer-down-main-box-language-icon
            %i.fas.fa-globe
        .footer-down-main-box-country
          .footer-down-main-box-country-icon
            = image_tag "/assets/日本.png",size:"16x12"
          .footer-down-main-box-country-title
            日本
  .footer-bottom
    .footer-bottom__ul
      %label.footer-bottom__ul__li
        = link_to "", class:"footer-bottom__ul__li-title" do
          Amazon Advertising
          %br/
          %span.footer-bottom__ul__li-text
            商品の露出でお客様の関心と
            %br/
            反応を引き出す
      .footer-bottom__ul__li
        = link_to "", class:"footer-bottom__ul__li-title" do
          Audible（オーディブル）
          %br/
          %span.footer-bottom__ul__li-text
            本は、聴こう。
            %br/
            最初の1冊は無料
      .footer-bottom__ul__li
        = link_to "", class:"footer-bottom__ul__li-title" do
          アマゾン ウェブ サービス（AWS）
          %br/
          %span.footer-bottom__ul__li-text
            クラウドコンピューティング
            %br/
            サービス
      .footer-bottom__ul__li
        = link_to "", class:"footer-bottom__ul__li-title" do
          Amazonアウトレット
          %br/
          %span.footer-bottom__ul__li-text
            訳あり商品を
            %br/
            お手頃価格で販売
    .footer-bottom__ul
      .footer-bottom__ul__li
        = link_to "", class:"footer-bottom__ul__li-title" do
          Prime Now
          %br/
          %span.footer-bottom__ul__li-text
            好きな時間が選べる
            %br/
            最短２時間で届く
      .footer-bottom__ul__li
        = link_to "", class:"footer-bottom__ul__li-title" do
          Amazonビジネス（法人購買）
          %br/
          %span.footer-bottom__ul__li-text
            請求書払い
            %br/
            法人価格・数量割引
      .footer-bottom__ul__li
        = link_to "", class:"footer-bottom__ul__li-title" do
          Book Depository
          %br/
          %span.footer-bottom__ul__li-text
            送料無料で
            %br/
            世界中にお届け
      .footer-bottom__ul__li
        = link_to "", class:"footer-bottom__ul__li-title" do
          Shopbop
          %br/
          %span.footer-bottom__ul__li-text
            世界中の厳選された
            %br/
            ファッションアイテム
  .footer-footer
    %ul.footer-footer-ul
      %li.footer-footer-ul-li
        = link_to "", class:"footer-footer-ul-li-link" do
          利用規約
      %li.footer-footer-ul-li-second
        = link_to "", class:"footer-footer-ul-li-link" do
          プライバシー規約
      %li.footer-footer-ul-li
        = link_to "", class:"footer-footer-ul-li-link" do
          パーソナライズド広告規約
    .footer-footer-offer
      © 1996-2020, Amazon.com, Inc. or its affiliates

app/views/posts/_header.html.haml
.header
  .header-upper
    .header-upper-title
      .header-upper-title-category
        %input#nav-input.nav-unshown{:type => "checkbox"}/
        %label#nav-open{:for => "nav-input"}
          %span
        %label#nav-close.nav-unshown{:for => "nav-input"}
        #nav-content ここに中身を入れる
      .header-upper-title-box
        .header-upper-title-box-main
          = link_to posts_path, class:"header-upper-title-box-main-amazon" do
            amazon
          .header-upper-title-box-main-domain .co.jp
        .header-upper-title-box-sub
          .header-upper-title-box-sub-right
            →
          - if user_signed_in?
            .header-upper-title-box-sub-right-prime
              prime
          - else
            = link_to new_user_registration_path, class:"header-upper-title-box-sub-prime" do
              プライムを始める
    .header-upper-search
      %select.header-upper-search-pulldown{name:"posts"}
        %option{:value => ""} Prime Video
      %input(type="textarea" class="header-upper-search-form")/
      %button(type="submit" class="header-upper-search-btn")
        %i.fas.fa-search
    .header-upper-user
      .header-upper-user-country
        .header-upper-user-country-name
          JP
        .header-upper-user-country-choice
          .header-upper-user-country-choice-icon
            %i.fas.fa-globe
          .header-upper-user-country-choice-icon
            %i.fas.fa-caret-down{style: "color: #AEB0B3"}
      .header-upper-user-login
        - if user_signed_in?
          .header-upper-user-login-username
            = current_user.name
            さん
          = link_to "新規投稿", new_user_session_path, class: "header-upper-user-login--btn"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-upper-user-login--btn"
        - else
          .header-upper-user-login-username
            こんにちは, ログイン
          = link_to "ログイン", new_user_session_path, class: "header-upper-user-login--btn"
          = link_to "新規登録", new_user_registration_path, class: "header-upper-user-login--btn"
      = link_to "", class:"header-upper-user-history" do
        注文履歴
      .header-upper-user-paidmember
        .header-upper-user-paidmember-confirmation
          今すぐ確認
        .header-upper-user-paidmember-member
          プライム
          %i.fas.fa-caret-down{style: "color: #AEB0B3"}
      .header-upper-user-cart
        .header-upper-user-cart-logo
          %i.fas.fa-shopping-cart
        .header-upper-user-cart-letter
          カート
  .header-lower
    .header-lower-address
      .header-lower-address-mark
        %i.fas.fa-map-marker-alt
      .header-lower-address-text
        .header-lower-address-text-user
          お届け先
          - if user_signed_in?
            %span.header-lower-address-text-user-name
              = current_user.name
            さん
        .header-lower-address-text-addressee
          お届け先を選択
    %ul.header-lower-lists
      %li.header-lower-lists__li
        もう一度買う
      %li.header-lower-lists__li
        マイストア
      %li.header-lower-lists__li
        タイムセール
      %li.header-lower-lists__li
        ギフト券
      %li.header-lower-lists__li
        Amazonで売る
      %li.header-lower-lists__li
        ヘルプ
      %li.header-lower-lists__li
        ドラッグストア
      %li.header-lower-lists__li
        本
      %li.header-lower-lists__li
        パソコン・周辺機器
    .header-lower-advertising
      .header-lower-advertising-image
        = image_tag "/assets/amazonmusic.png"

    

app/views/posts/_showupper.html.haml
.show-upper-details
  .show-upper-details-left
    .show-upper-details-left-title
      = @work.title
    .show-upper-details-left-evaluation
      - if @posts.blank?
        まだ評価をつけられておりません
      - else
        %div.rate-average
          :javascript
            $(".rate-average").raty({
              size: 36,
              starOff:  '#{asset_path('star-off.png')}',
              starOn : '#{asset_path('star-on.png')}',
              starHalf: '#{asset_path('star-half.png')}',
              half: true,
              readOnly: true,
              score: #{Post.average_rate(@posts).round(1)}
            });
        .show-upper-details-left-evaluation-length
          = "(#{@posts.length})"
        .show-upper-details-left-evaluation-release
          = "#{@work.release}年"
    .show-upper-details-left-text
      = @work.content
    .show-upper-details-left-starring
      .show-upper-details-left-starring-title
        主演
      = link_to "", class:"show-upper-details-left-starring-name" do
        = @work.starring
  .show-upper-details-right
    = image_tag @work.image.url, size:"335x215"

app/views/posts/_slide.html.haml
.content-main-slides
  .content-main-slides-slide
    =link_to post_path(1), class:"content-main-slides-slide-1" do
      =image_tag "/assets/slidechild1.jpg", size:"320x185"
  .content-main-slides-slide
    =link_to post_path(2), class:"content-main-slides-slide-1" do
      =image_tag "/assets/slidechild2.jpg", size:"330x185"
  .content-main-slides-slide
    =link_to post_path(3), class:"content-main-slides-slide-1" do
      =image_tag "/assets/slidechild3.jpg", size:"330x185"
  .content-main-slides-slide
    =link_to post_path(4), class:"content-main-slides-slide-1" do
      =image_tag "/assets/slidechild4.jpg", size:"330x185"
  .content-main-slides-slide
    =link_to post_path(5), class:"content-main-slides-slide-1" do
      =image_tag "/assets/slidechild5.jpg", size:"330x185"
  .content-main-slides-slide
    =link_to post_path(6), class:"content-main-slides-slide-1" do
      =image_tag "/assets/slidechild6.jpg", size:"330x185"
  .content-main-slides-slide
    =link_to post_path(7), class:"content-main-slides-slide-1" do
      =image_tag "/assets/slidechild7.jpg", size:"330x185"
  .content-main-slides-slide
    =link_to post_path(8), class:"content-main-slides-slide-1" do
      =image_tag "/assets/slidechild8.jpg", size:"330x185"

app/views/posts/index.html.haml
.index
  .slider
    .slide
      =link_to post_path(9) do
        =image_tag "/assets/slide1.jpg"
    .slide
      =link_to post_path(4) do
        =image_tag "/assets/slide2.jpg"
    .slide
      =link_to post_path(11) do
        =image_tag "/assets/slide3.jpg"
    .slide
      =link_to post_path(10) do
        =image_tag "/assets/slide4.jpg"

  .content
    .content-main
      .content-main-titles
        .content-main-titles-prime
          prime
        .content-main-titles-title
          最近追加された作品
      = render partial: 'slide'
    .content-main
      .content-main-titles
        .content-main-titles-prime
          prime
        .content-main-titles-title
          おすすめ作品
      = render 'slide'
    .content-main
      .content-main-titles
        .content-main-titles-prime
          prime
        .content-main-titles-title
          最近追加された作品
      = render 'slide'

app/views/posts/show.html.haml
.show-upper
  = render 'showupper'
  .content-main-titles
    .content-main-titles-prime
      prime
    .content-main-titles-title
      最近追加された作品
  = render 'slide'
  .show-upper-bottom

.show-down
  .show-down-left
    .show-down-left-up
      .show-down-left-up-title
        カスタマーレビュー
      .show-down-left-up-box
        - if @posts.blank?
          まだ評価をつけられておりません
        - else
          .show-down-left-up-box-star
            %div.rate-average
              :javascript
                $('.rate-average').raty({
                  size: 36,
                  starOff:  '#{asset_path('star-off.png')}',
                  starOn : '#{asset_path('star-on.png')}',
                  starHalf: '#{asset_path('star-half.png')}',
                  half: true,
                  readOnly: true,
                  score: #{Post.average_rate(@posts).round(1)}
                });
          .show-down-left-up-box-rate
            星5つ中の
            = Post.average_rate(@posts).round(1)
          .show-down-left-up-box-pull
            %i.fas.fa-angle-down
      .show-down-left-up-total
        評価の数#{@posts.length}
      .show-down-left-up-rating
        .show-down-left-up-rating-link
          星5つ
        .show-down-left-up-rating-graph
          .show-down-left-up-rating-graph-length
        .show-down-left-up-rating-percent
          11%
      .show-down-left-up-rating
        .show-down-left-up-rating-link
          星4つ
        .show-down-left-up-rating-graph
        .show-down-left-up-rating-percent
          11%
      .show-down-left-up-rating
        .show-down-left-up-rating-link
          星3つ
        .show-down-left-up-rating-graph
        .show-down-left-up-rating-percent
          11%
      .show-down-left-up-rating
        .show-down-left-up-rating-link
          星2つ
        .show-down-left-up-rating-graph
        .show-down-left-up-rating-percent
          11%
      .show-down-left-up-rating
        .show-down-left-up-rating-link
          星1つ
        .show-down-left-up-rating-graph
        .show-down-left-up-rating-percent
          11%


    .show-down-left-down
      .show-down-left-down-title
        この商品をレビュー
      .show-down-left-down-sub
        他のお客様にも意見を伝えましょう
      %button.show-down-left-down-button
        = link_to new_post_path(@work.id), class:"show-down-left-down-button-link"do
          カスタマーレビューを書く
          
  .show-down-right
    .show-down-right-main
      .show-down-right-main-box
        - @posts.each do |p|
          .show-down-right-main-box-name
            .show-down-right-main-box-name-image
              = image_tag "/assets/user_image.jpeg", size:"30x30"
            .show-down-right-main-box-name-name
              = p.user.name
          .show-down-right-main-box-titles
            .show-down-right-main-box-titles-rate
              -# / 星評価
              %div{:id => "star-rate-#{p.id}"}
                :javascript
                  $('#star-rate-#{p.id}').raty({
                    size: 36,
                    starOff:  '#{asset_path('star-off.png')}',
                    starOn : '#{asset_path('star-on.png')}',
                    half: true,
                    readOnly: true,
                    score: #{p.rate}
                  });
                / /星評価
            .show-down-right-main-box-titles-title
              = p.title
          .show-down-right-main-box-create
            = p.created_at.strftime('%Y年%m月%d日')
            にレビュー済み
          .show-down-right-main-box-comment
            = safe_join(p.content.split("\n"),tag(:br))
          .show-down-right-main-box-useful
            #{p.likes.count}人のお客様がこれが役に立ったと考えています
          .show-down-right-main-box-rate
            -# %button.show-down-right-main-box-rate-button
              -# 役に立った
            - if current_user.already_liked?(p)
              .show-down-right-main-box-rate-check
                %i.fas.fa-check{style: "color:green"}
                フィードバックをお寄せいただきありがとうございます。
              -# = button_to '役に立ったを取り消す', post_like_path(p.id), method: :delete, class:"show-down-right-main-box-rate-button"
            - else
              = button_to '役に立った', post_likes_path(p.id), class:"show-down-right-main-box-rate-button"
            .show-down-right-main-box-rate-comment
              コメント
            .show-down-right-main-box-rate-report
              違反を報告

app/views/works/new.html.haml
= form_for @works, url: works_path, method: :post, html: {class: 'works'} do |f|
  = f.text_field :title
  = f.text_field :content
  = f.number_field :release
  = f.text_field :starring
  = f.file_field :image
  = f.submit '投稿する'